name: Amul Product Availability Checker

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Log script start
        run: echo "Running Amul Product Availability Checker at $(date)"

      - name: Run product availability checker
        run: node amulprtnfinder.js
        working-directory: backend
        env: 
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
